/**
 * PDF Download Hook
 *
 * Provides a function to download PDFs generated by the server-side API.
 */

import { useState, useCallback } from "react";
import type { Id } from "../../convex/_generated/dataModel";

interface UsePdfDownloadResult {
  downloadPdf: (projectId: Id<"projects">, fileName: string) => Promise<void>;
  isGenerating: boolean;
  error: string | null;
  clearError: () => void;
}

export function usePdfDownload(): UsePdfDownloadResult {
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const clearError = useCallback(() => {
    setError(null);
  }, []);

  const downloadPdf = useCallback(
    async (projectId: Id<"projects">, fileName: string) => {
      setIsGenerating(true);
      setError(null);

      try {
        const response = await fetch("/api/pdf/generate", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ projectId }),
        });

        if (!response.ok) {
          // Try to get error message from response
          const errorData = await response.json().catch(() => ({}));
          const errorMessage =
            errorData.error ||
            `Failed to generate PDF (${response.status})`;

          // Handle rate limiting specially
          if (response.status === 429) {
            const retryAfter = errorData.retryAfter || 60;
            throw new Error(
              `Too many requests. Please try again in ${retryAfter} seconds.`
            );
          }

          throw new Error(errorMessage);
        }

        // Get the PDF blob
        const blob = await response.blob();

        // Verify it's actually a PDF
        if (!blob.type.includes("pdf") && blob.type !== "application/pdf") {
          throw new Error("Server did not return a valid PDF");
        }

        // Create download link
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = fileName;

        // Trigger download
        document.body.appendChild(link);
        link.click();

        // Cleanup
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
      } catch (err) {
        const message =
          err instanceof Error ? err.message : "Failed to download PDF";
        setError(message);
        console.error("[PDF_DOWNLOAD_ERROR]", err);
      } finally {
        setIsGenerating(false);
      }
    },
    []
  );

  return {
    downloadPdf,
    isGenerating,
    error,
    clearError,
  };
}
